
#define SYSCALL_read    0       
#define SYSCALL_write   1       
#define SYSCALL_open    2       
#define SYSCALL_close   3       
#define SYSCALL_stat    4       
#define SYSCALL_fstat   5       
#define SYSCALL_lstat   6       
#define SYSCALL_poll    7       
#define SYSCALL_lseek   8       
#define SYSCALL_mmap    9       
#define SYSCALL_mprotect    10      
#define SYSCALL_munmap  11      
#define SYSCALL_brk 12      
#define SYSCALL_rt_sigaction    13      
#define SYSCALL_rt_sigprocmask  14      
#define SYSCALL_rt_sigreturn    15      
#define SYSCALL_ioctl   16      
#define SYSCALL_pread64 17      
#define SYSCALL_pwrite64    18      
#define SYSCALL_readv   19      
#define SYSCALL_writev  20      
#define SYSCALL_access  21      
#define SYSCALL_pipe    22      
#define SYSCALL_select  23      
#define SYSCALL_sched_yield 24      
#define SYSCALL_mremap  25      
#define SYSCALL_msync   26      
#define SYSCALL_mincore 27      
#define SYSCALL_madvise 28      
#define SYSCALL_shmget  29      
#define SYSCALL_shmat   30      
#define SYSCALL_shmctl  31      
#define SYSCALL_dup 32      
#define SYSCALL_dup2    33      
#define SYSCALL_pause   34      
#define SYSCALL_nanosleep   35      
#define SYSCALL_getitimer   36      
#define SYSCALL_alarm   37      
#define SYSCALL_setitimer   38      
#define SYSCALL_getpid  39      
#define SYSCALL_sendfile    40      
#define SYSCALL_socket  41      
#define SYSCALL_connect 42      
#define SYSCALL_accept  43      
#define SYSCALL_sendto  44      
#define SYSCALL_recvfrom    45      
#define SYSCALL_sendmsg 46      
#define SYSCALL_recvmsg 47      
#define SYSCALL_shutdown    48      
#define SYSCALL_bind    49      
#define SYSCALL_listen  50      
#define SYSCALL_getsockname 51      
#define SYSCALL_getpeername 52      
#define SYSCALL_socketpair  53      
#define SYSCALL_setsockopt  54      
#define SYSCALL_getsockopt  55      
#define SYSCALL_clone   56      
#define SYSCALL_fork    57      
#define SYSCALL_vfork   58      
#define SYSCALL_execve  59      
#define SYSCALL_exit    60      
#define SYSCALL_wait4   61      
#define SYSCALL_kill    62      
#define SYSCALL_uname   63      
#define SYSCALL_semget  64      
#define SYSCALL_semop   65      
#define SYSCALL_semctl  66      
#define SYSCALL_shmdt   67      
#define SYSCALL_msgget  68      
#define SYSCALL_msgsnd  69      
#define SYSCALL_msgrcv  70      
#define SYSCALL_msgctl  71      
#define SYSCALL_fcntl   72      
#define SYSCALL_flock   73      
#define SYSCALL_fsync   74      
#define SYSCALL_fdatasync   75      
#define SYSCALL_truncate    76      
#define SYSCALL_ftruncate   77      
#define SYSCALL_getdents    78      
#define SYSCALL_getcwd  79      
#define SYSCALL_chdir   80      
#define SYSCALL_fchdir  81      
#define SYSCALL_rename  82      
#define SYSCALL_mkdir   83      
#define SYSCALL_rmdir   84      
#define SYSCALL_creat   85      
#define SYSCALL_link    86      
#define SYSCALL_unlink  87      
#define SYSCALL_symlink 88      
#define SYSCALL_readlink    89      
#define SYSCALL_chmod   90      
#define SYSCALL_fchmod  91      
#define SYSCALL_chown   92      
#define SYSCALL_fchown  93      
#define SYSCALL_lchown  94      
#define SYSCALL_umask   95      
#define SYSCALL_gettimeofday    96      
#define SYSCALL_getrlimit   97      
#define SYSCALL_getrusage   98      
#define SYSCALL_sysinfo 99      
#define SYSCALL_times   100     
#define SYSCALL_ptrace  101     
#define SYSCALL_getuid  102     
#define SYSCALL_syslog  103     
#define SYSCALL_getgid  104     
#define SYSCALL_setuid  105     
#define SYSCALL_setgid  106     
#define SYSCALL_geteuid 107     
#define SYSCALL_getegid 108     
#define SYSCALL_setpgid 109     
#define SYSCALL_getppid 110     
#define SYSCALL_getpgrp 111     
#define SYSCALL_setsid  112     
#define SYSCALL_setreuid    113     
#define SYSCALL_setregid    114     
#define SYSCALL_getgroups   115     
#define SYSCALL_setgroups   116     
#define SYSCALL_setresuid   117     
#define SYSCALL_getresuid   118     
#define SYSCALL_setresgid   119     
#define SYSCALL_getresgid   120     
#define SYSCALL_getpgid 121     
#define SYSCALL_setfsuid    122     
#define SYSCALL_setfsgid    123     
#define SYSCALL_getsid  124     
#define SYSCALL_capget  125     
#define SYSCALL_capset  126     
#define SYSCALL_rt_sigpending   127     
#define SYSCALL_rt_sigtimedwait 128     
#define SYSCALL_rt_sigqueueinfo 129     
#define SYSCALL_rt_sigsuspend   130     
#define SYSCALL_sigaltstack 131     
#define SYSCALL_utime   132     
#define SYSCALL_mknod   133     
#define SYSCALL_uselib  134     
#define SYSCALL_personality 135     
#define SYSCALL_ustat   136     
#define SYSCALL_statfs  137     
#define SYSCALL_fstatfs 138     
#define SYSCALL_sysfs   139     
#define SYSCALL_getpriority 140     
#define SYSCALL_setpriority 141     
#define SYSCALL_sched_setparam  142     
#define SYSCALL_sched_getparam  143     
#define SYSCALL_sched_setscheduler  144     
#define SYSCALL_sched_getscheduler  145     
#define SYSCALL_sched_get_priority_max  146     
#define SYSCALL_sched_get_priority_min  147     
#define SYSCALL_sched_rr_get_interval   148     
#define SYSCALL_mlock   149     
#define SYSCALL_munlock 150     
#define SYSCALL_mlockall    151     
#define SYSCALL_munlockall  152     
#define SYSCALL_vhangup 153     
#define SYSCALL_modify_ldt  154     
#define SYSCALL_pivot_root  155     
#define SYSCALL__sysctl 156     
#define SYSCALL_prctl   157     
#define SYSCALL_arch_prctl  158     
#define SYSCALL_adjtimex    159     
#define SYSCALL_setrlimit   160     
#define SYSCALL_chroot  161     
#define SYSCALL_sync    162     
#define SYSCALL_acct    163     
#define SYSCALL_settimeofday    164     
#define SYSCALL_mount   165     
#define SYSCALL_umount2 166     
#define SYSCALL_swapon  167     
#define SYSCALL_swapoff 168     
#define SYSCALL_reboot  169     
#define SYSCALL_sethostname 170     
#define SYSCALL_setdomainname   171     
#define SYSCALL_iopl    172     
#define SYSCALL_ioperm  173     
#define SYSCALL_create_module   174     
#define SYSCALL_init_module 175     
#define SYSCALL_delete_module   176     
#define SYSCALL_get_kernel_syms 177     
#define SYSCALL_query_module    178     
#define SYSCALL_quotactl    179     
#define SYSCALL_nfsservctl  180     
#define SYSCALL_getpmsg 181     
#define SYSCALL_putpmsg 182     
#define SYSCALL_afs_syscall 183     
#define SYSCALL_tuxcall 184     
#define SYSCALL_security    185     
#define SYSCALL_gettid  186     
#define SYSCALL_readahead   187     
#define SYSCALL_setxattr    188     
#define SYSCALL_lsetxattr   189     
#define SYSCALL_fsetxattr   190     
#define SYSCALL_getxattr    191     
#define SYSCALL_lgetxattr   192     
#define SYSCALL_fgetxattr   193     
#define SYSCALL_listxattr   194     
#define SYSCALL_llistxattr  195     
#define SYSCALL_flistxattr  196     
#define SYSCALL_removexattr 197     
#define SYSCALL_lremovexattr    198     
#define SYSCALL_fremovexattr    199     
#define SYSCALL_tkill   200     
#define SYSCALL_time    201     
#define SYSCALL_futex   202     
#define SYSCALL_sched_setaffinity   203     
#define SYSCALL_sched_getaffinity   204     
#define SYSCALL_set_thread_area 205     
#define SYSCALL_io_setup    206     
#define SYSCALL_io_destroy  207     
#define SYSCALL_io_getevents    208     
#define SYSCALL_io_submit   209     
#define SYSCALL_io_cancel   210     
#define SYSCALL_get_thread_area 211     
#define SYSCALL_lookup_dcookie  212     
#define SYSCALL_epoll_create    213     
#define SYSCALL_epoll_ctl_old   214     
#define SYSCALL_epoll_wait_old  215     
#define SYSCALL_remap_file_pages    216     
#define SYSCALL_getdents64  217     
#define SYSCALL_set_tid_address 218     
#define SYSCALL_restart_syscall 219     
#define SYSCALL_semtimedop  220     
#define SYSCALL_fadvise64   221     
#define SYSCALL_timer_create    222     
#define SYSCALL_timer_settime   223     
#define SYSCALL_timer_gettime   224     
#define SYSCALL_timer_getoverrun    225     
#define SYSCALL_timer_delete    226     
#define SYSCALL_clock_settime   227     
#define SYSCALL_clock_gettime   228     
#define SYSCALL_clock_getres    229     
#define SYSCALL_clock_nanosleep 230     
#define SYSCALL_exit_group  231     
#define SYSCALL_epoll_wait  232     
#define SYSCALL_epoll_ctl   233     
#define SYSCALL_tgkill  234     
#define SYSCALL_utimes  235     
#define SYSCALL_vserver 236     
#define SYSCALL_mbind   237     
#define SYSCALL_set_mempolicy   238     
#define SYSCALL_get_mempolicy   239     
#define SYSCALL_mq_open 240     
#define SYSCALL_mq_unlink   241     
#define SYSCALL_mq_timedsend    242     
#define SYSCALL_mq_timedreceive 243     
#define SYSCALL_mq_notify   244     
#define SYSCALL_mq_getsetattr   245     
#define SYSCALL_kexec_load  246     
#define SYSCALL_waitid  247     
#define SYSCALL_add_key 248     
#define SYSCALL_request_key 249     
#define SYSCALL_keyctl  250     
#define SYSCALL_ioprio_set  251     
#define SYSCALL_ioprio_get  252     
#define SYSCALL_inotify_init    253     
#define SYSCALL_inotify_add_watch   254     
#define SYSCALL_inotify_rm_watch    255     
#define SYSCALL_migrate_pages   256     
#define SYSCALL_openat  257     
#define SYSCALL_mkdirat 258     
#define SYSCALL_mknodat 259     
#define SYSCALL_fchownat    260     
#define SYSCALL_futimesat   261     
#define SYSCALL_newfstatat  262     
#define SYSCALL_unlinkat    263     
#define SYSCALL_renameat    264     
#define SYSCALL_linkat  265     
#define SYSCALL_symlinkat   266     
#define SYSCALL_readlinkat  267     
#define SYSCALL_fchmodat    268     
#define SYSCALL_faccessat   269     
#define SYSCALL_pselect6    270     
#define SYSCALL_ppoll   271     
#define SYSCALL_unshare 272     
#define SYSCALL_set_robust_list 273     
#define SYSCALL_get_robust_list 274     
#define SYSCALL_splice  275     
#define SYSCALL_tee 276     
#define SYSCALL_sync_file_range 277     
#define SYSCALL_vmsplice    278     
#define SYSCALL_move_pages  279     
#define SYSCALL_utimensat   280     
#define SYSCALL_epoll_pwait 281     
#define SYSCALL_signalfd    282     
#define SYSCALL_timerfd_create  283     
#define SYSCALL_eventfd 284     
#define SYSCALL_fallocate   285     
#define SYSCALL_timerfd_settime 286     
#define SYSCALL_timerfd_gettime 287     
#define SYSCALL_accept4 288     
#define SYSCALL_signalfd4   289     
#define SYSCALL_eventfd2    290     
#define SYSCALL_epoll_create1   291     
#define SYSCALL_dup3    292     
#define SYSCALL_pipe2   293     
#define SYSCALL_inotify_init1   294     
#define SYSCALL_preadv  295     
#define SYSCALL_pwritev 296     
#define SYSCALL_rt_tgsigqueueinfo   297     
#define SYSCALL_perf_event_open 298     
#define SYSCALL_recvmmsg    299     
#define SYSCALL_fanotify_init   300     
#define SYSCALL_fanotify_mark   301     
#define SYSCALL_prlimit64   302     
#define SYSCALL_name_to_handle_at   303     
#define SYSCALL_open_by_handle_at   304     
#define SYSCALL_clock_adjtime   305     
#define SYSCALL_syncfs  306     
#define SYSCALL_sendmmsg    307     
#define SYSCALL_setns   308     
#define SYSCALL_getcpu  309     
#define SYSCALL_process_vm_readv    310     
#define SYSCALL_process_vm_writev   311     
#define SYSCALL_kcmp    312     
#define SYSCALL_finit_module    313     
#define SYSCALL_sched_setattr   314     
#define SYSCALL_sched_getattr   315     
#define SYSCALL_renameat2   316     
#define SYSCALL_seccomp 317     
#define SYSCALL_getrandom   318     
#define SYSCALL_memfd_create    319     
#define SYSCALL_kexec_file_load 320     
#define SYSCALL_bpf 321     
#define SYSCALL_execveat    322     
#define SYSCALL_userfaultfd 323     
#define SYSCALL_membarrier  324     
#define SYSCALL_mlock2  325     
#define SYSCALL_copy_file_range 326     
#define SYSCALL_preadv2 327     
#define SYSCALL_pwritev2    328     
#define SYSCALL_pkey_mprotect   329     
#define SYSCALL_pkey_alloc  330     
#define SYSCALL_pkey_free   331     
#define SYSCALL_statx   332     
#define SYSCALL_io_pgetevents   333     
#define SYSCALL_rseq    334         
#define SYSCALL_pidfd_send_signal   424     
#define SYSCALL_io_uring_setup  425     
#define SYSCALL_io_uring_enter  426     
#define SYSCALL_io_uring_register   427     
#define SYSCALL_open_tree   428     
#define SYSCALL_move_mount  429     
#define SYSCALL_fsopen  430     
#define SYSCALL_fsconfig    431     
#define SYSCALL_fsmount 432     
#define SYSCALL_fspick  433     
#define SYSCALL_pidfd_open  434     
#define SYSCALL_clone3  435     
